### ISSUE TITLE
"full window content" overlaps window border on Windows 10

### ISSUE THREAD

**Issue by ShadelessFox** [JFormDesigner/FlatLaf#809]
Running on Windows 10 21H2 (19044.1526). The following screenshot perfectly illustrates the issue:

![javaw_h5aFirJRfS](https://github.com/JFormDesigner/FlatLaf/assets/35821147/3fd0d018-ce30-4e3b-8bbd-d8620ec0d8c8)

**Comment by NerdyPuzzle** [comment]
Can confirm this issue persists on windows 10

**Comment by NerdyPuzzle** [comment]
Can confirm this issue persists on windows 10 ![image-12.png](https://github.com/JFormDesigner/FlatLaf/assets/112079900/ca494b03-e865-4779-a9ec-000d7ccc6867)

This issue is more clear here due to the pink border

**Comment by DevCharly** [comment]
Thanks for reporting.

fixed in latest `3.5-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by KlemenDEV** [comment]
Thank you for the fix!

**Comment by KlemenDEV** [comment]
It some cases it still happens:

![image](https://github.com/JFormDesigner/FlatLaf/assets/16374228/0be62e2d-77ab-4707-9c2d-44b3919f457f)

Resizing the window seems to fix the issue

**Comment by DJ-Raven** [comment]
Yes, It still happens when windows frame has lose focus, I test the demo pull latest update.
